extends:
  - airbnb-base
  - plugin:vue/recommended
  - prettier
  - prettier/vue
parserOptions:
  parser: babel-eslint
globals:
  rqevent: true
rules:
  no-restricted-globals:
    - off
  import/prefer-default-export:
    - off
  func-names:
    - off
  no-nested-ternary:
    - off
  no-multi-assign:
    - off
  no-throw-literal:
    - off
  no-param-reassign:
    - error
    - props: false
  no-shadow:
    - error
    - allow:
        - state
  no-unused-expressions:
    - error
    - allowShortCircuit: true
      allowTernary: true
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  import/no-extraneous-dependencies:
    - off
  # parcel support
  import/no-absolute-path:
    - off
  import/no-unresolved:
    - off
  # experiment
  complexity:
    - error
    - 11
