extends:
  - stylelint-config-standard-scss
  - stylelint-config-prettier
overrides:
  - files:
      - "**/*.vue"
    customSyntax: postcss-html
rules:
  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
        - v-deep
  selector-class-pattern:
    - "^([a-z][a-z0-9]*)((-|_)+[a-z0-9]+)*$"
    - message: "Expected class selector to be kebab-case"
