import "../assets/icon/iconfont.css";
import "../assets/icon/iconfont.woff2";
import "../assets/icon/iconfont.woff";
import "../assets/icon/iconfont.eot";
import "../assets/icon/iconfont.ttf";
import "../assets/icon/iconfont.svg";
import "../assets/icon-svg/iconfont";
import "../assets/icon-svg/iconfont.css";
import "./variables.css";
